# Generated by Django 5.0.9 on 2024-10-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('day_name', models.CharField(max_length=10, unique=True)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='asset',
            name='work_days',
        ),
        migrations.AddField(
            model_name='asset',
            name='work_days',
            field=models.ManyToManyField(blank=True, to='application.dayofweek'),
        ),
    ]
