# Generated by Django 5.0.9 on 2024-10-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_projectstatus_taskstatus_remove_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='application.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='original_target_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical'), (5, 'Urgent')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.asset'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.projectstatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='revised_target_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='application.asset'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dependant_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='application.task'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
