# Generated by Django 5.0.9 on 2024-10-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_project_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='original_target_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='revised_target_end_date',
            field=models.DateField(null=True),
        ),
    ]
