# Generated by Django 5.0.9 on 2024-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_project_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='halo_ref',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='halo_ref',
            field=models.IntegerField(null=True),
        ),
    ]
