# Generated by Django 5.0.9 on 2024-10-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_project_halo_ref_task_halo_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_details',
            field=models.TextField(null=True),
        ),
    ]
