# Generated by Django 5.0.9 on 2024-10-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_project_project_description_task_task_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=50),
        ),
    ]
