# Generated by Django 5.0.9 on 2024-10-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_assumption_dependency_issue_risk_stakeholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assumption',
            options={'verbose_name': 'Assumption', 'verbose_name_plural': 'Assumptions'},
        ),
        migrations.AlterModelOptions(
            name='dependency',
            options={'verbose_name': 'Dependency', 'verbose_name_plural': 'Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterModelOptions(
            name='risk',
            options={'verbose_name': 'Risk', 'verbose_name_plural': 'Risks'},
        ),
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'verbose_name': 'Stakeholder', 'verbose_name_plural': 'Stakeholders'},
        ),
    ]
