# Generated by Django 5.0.9 on 2024-10-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_rename_project_id_project_id_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='id',
        ),
    ]
