# Generated by Django 5.0.9 on 2024-10-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_rename_task_id_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='risk_id',
            new_name='id',
        ),
    ]
