# Generated by Django 5.0.9 on 2024-10-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_risk_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={},
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_id',
            new_name='id',
        ),
    ]
