# Generated by Django 5.0.9 on 2024-10-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_alter_issue_options_rename_issue_id_issue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependency',
            old_name='dependency_id',
            new_name='id',
        ),
    ]
