# Generated by Django 5.0.9 on 2024-10-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_rename_dependency_id_dependency_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependency',
            options={},
        ),
    ]
