# Generated by Django 5.0.9 on 2024-10-14 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_alter_task_assigned_to_alter_task_dependant_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.asset'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dependant_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.task'),
        ),
    ]
