# Generated by Django 5.0.9 on 2024-10-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_alter_task_assigned_to_alter_task_dependant_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstakeholder',
            old_name='stakeholder_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='stakeholder_id',
            new_name='id',
        ),
    ]
