# Generated by Django 5.0.9 on 2024-10-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_rename_stakeholder_id_historicalstakeholder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumption',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Closed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependency',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Closed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassumption',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Closed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldependency',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Closed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Closed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Closed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Closed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Closed')], default=1),
            preserve_default=False,
        ),
    ]
