# Generated by Django 5.0.9 on 2024-10-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_remove_attachment_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaskstatus',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Awaiting Closure'), (3, 'In Progress'), (4, 'On Hold'), (5, 'Scoping'), (6, 'Responded'), (7, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Awaiting Closure'), (3, 'In Progress'), (4, 'On Hold'), (5, 'Scoping'), (6, 'Responded'), (7, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='task_status',
            field=models.IntegerField(choices=[(1, 'Unassigned'), (2, 'Assigned'), (3, 'Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(1, 'Unassigned'), (2, 'Assigned'), (3, 'Completed')], default=1),
        ),
        migrations.DeleteModel(
            name='HistoricalProjectStatus',
        ),
        migrations.DeleteModel(
            name='HistoricalTaskStatus',
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
