# Generated by Django 5.0.9 on 2024-11-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_remove_historicaltaskstatus_history_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltask',
            old_name='dependant_task',
            new_name='prereq_task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='dependant_task',
            new_name='prereq_task',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='has_dependency',
        ),
        migrations.RemoveField(
            model_name='task',
            name='has_dependency',
        ),
    ]
